language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE pyhusky;'
install: python setup.py install
script:
- python tests/test_exceptions.py
- python tests/test_migrations.py
matrix:
  allow_failures:
    - python: 3.2